package dev.linqfy.bigCasares.modules.grapplinghook;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/** Suppresses the duplicate interact/fishing events generated by one click. */
public final class GrapplingHookInputGate {

    private final long windowMillis;
    private final Map<UUID, Long> lastInputByPlayer = new HashMap<>();

    public GrapplingHookInputGate(long windowMillis) {
        this.windowMillis = Math.max(0L, windowMillis);
    }

    public boolean tryAcquire(UUID playerId, long nowMillis) {
        if (playerId == null) {
            return false;
        }
        Long previous = lastInputByPlayer.get(playerId);
        if (previous != null && nowMillis >= previous && nowMillis - previous < windowMillis) {
            return false;
        }
        lastInputByPlayer.put(playerId, nowMillis);
        return true;
    }

    public void remove(UUID playerId) {
        if (playerId != null) {
            lastInputByPlayer.remove(playerId);
        }
    }
}
